#Generator 

* 特征一是，function关键字与函数名之间有一个星号；

> function* fn(){}

* 二是，函数体内部使用yield表达式，定义不同的内部状态（yield在英语里的意思就是“产出”）。

```
function* fn(){
    yield 4;
    return 5;
}

```

* Generator 函数可以不用yield表达式，这时就变成了一个单纯的暂缓执行函数。

```
    //当前这个fn是一个暂缓执行的函数，一开始是不执行的，只有调用了next方法才执行函数内的代码
    function* fn(){
        console.log(111);
    }
    let f = fn();

    setTimeout(()=>{
        f.next();
    },1000)

```
```
var arr = [1, [[2, 3], 4], [5, 6]];
        function* flat(a) {
            var length = a.length; //数组的length
            for (var i = 0; i < length; i++) {
                var item = a[i]; //数组的每一项
                if (typeof item !== 'number') {
                    yield* flat(item);
                } else {
                    yield item;
                }
            }
        };
        for (var f of flat(arr)) {
            console.log(f);//1 2 3 4 5 6
        }
        for of 默认自动执行next方法
```
```
 function* fn() {
            yield 1;
            yield 2;
            yield 3;
            return 4;
        }
        let t = fn();
        for (let attr of t) {
            console.log(attr);//1 2 3
        }
       //console.log([...t]);//[1,2,3]
       for of和 扩展运算符 默认自动执行next方法
```

> yield表达式本身没有返回值，或者说总是返回undefined。next方法可以带一个参数，该参数就会被当作上一个yield表达式的返回值。
```
  function* f() {
            for (var i = 0; true; i++) {
                var reset = yield i;
                console.log(reset); 
                if (reset) {
                    i = -1;
                }
            }
        }
        var g = f();
        console.log(g.next()) // { value: 0, done: false }
        console.log(g.next()) // { value: 1, done: false }
        console.log(g.next(true)) // { value: 0, done: false }
        console.log(g.next());//{value: 1, done: false}
```

#### yield做了2件事
        
> 1.给value设置值  {value:0,done:false}

> 2.给reset返回了一个undefined

```

function* numbers () {
  yield 1
  yield 2
  return 3
  yield 4
}

// 扩展运算符
[...numbers()] // [1, 2]

// Array.from 方法
Array.from(numbers()) // [1, 2]

// 解构赋值
let [x, y] = numbers();
x // 1
y // 2

// for...of 循环
for (let n of numbers()) {
  console.log(n)
}
// 1
// 2

```


* 第一步，协程A开始执行。
* 第二步，协程A执行到一半，进入暂停，执行权转移到协程B。
* 第三步，（一段时间后）协程B交还执行权。
* 第四步，协程A恢复执行。
```
#### async把异步编程变成了同步编程
```
let a = 10;
 async function fn(){
     console.log(1);
     let aaa = await ff();
     console.log(aaa);
     a++;
     console.log(a);
 }

 fn();

function ff(){
    return new Promise((resolve)=>{
        setTimeout(function(){
            a ++;
            resolve(a);
        },2000)
    });
}
//结果为1 11 12
```
```
let a =10;
 async function fn(){
        console.log('.....');
        a = await promiseTime(); //11
        a ++ ;
        console.log(a);//12
    }
    fn();
    function promiseTime(){
        return new Promise((resolve)=>{
            setTimeout(() => {
                a ++;
                resolve(a);
            }, 3000);
        });
    }

    console.log(a);
```
#### 注意
```
  Promise.resolve('foo')
  // 等价于
  new Promise(resolve => resolve('foo'))

  console.log(Promise.resolve())

  new Promise(resolve => resolve())

  then方法一定是在Promise对象下的。
  如果说then有return， 如果return后是promise对象
  那么再then，是基于return后这个promise对象的
  如果return后并不是promise对象，那么promise对象
  往上找，如果下面还有then,成功的结果为上面then中return的值
  如果没有return，then的点前面是什么就是什么
```
```
then中的return不能返回Promise实例，不然会报错(死循环)
 const promise = Promise.resolve()
     .then(()=>{
        return promise;
     });
     promise.catch(console.error);
```
```
如果说then中传入的值为非函数，那么会穿透
then最后的结果是上一个promise成功的结果
  Promise.resolve(1)
     .then(()=>Promise.resolve(3))
     .then(2)
     .then(Promise.resolve(5))
     .then(Promise.resolve(6))
     .then((res)=>{
         console.log(res);//3
     });
```

